export const CHANGE_CLASSIFICATION = {
  TYPE_CHANGE: "TYPE_CHANGE",
  UNSTABLE_CALLBACK: "UNSTABLE_CALLBACK",
  CALLBACK_CHANGE: "CALLBACK_CHANGE",
  UNSTABLE_REFERENCE: "UNSTABLE_REFERENCE",
  VALUE_CHANGE: "VALUE_CHANGE",
  PRIMITIVE_CHANGE: "PRIMITIVE_CHANGE",
};
